FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm build

CMD ["pnpm", "run", "start-user-app"]