name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.user-app
          push: true
          tags: naviava/cashx-user-app:latest # Replace with your Docker Hub username and repository

      - name: Verify Pushed Image
        run: docker pull naviava/cashx-user-app:latest # Replace with your Docker Hub username and repository

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull naviava/cashx-user-app:latest
            docker stop cashx-user-app || true
            docker rm cashx-user-app || true
            docker run -d --name cashx-user-app -p 3005:3000 naviava/cashx-user-app:latest
